name: Do things every 5 minutes
on:
  schedule:    
    - cron: "*/5 8-20 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  call:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      CHANNEL_URL: ${{ secrets.SLACK_URL }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          RESULT=$(curl --silent 'https://www.interchangefinancial.com/api/index.php' \
          -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0' \
          -H 'Accept: */*' \
          -H 'Accept-Language: en-CA,en-US;q=0.7,en;q=0.3' \
          --compressed \
          -H 'Referer: https://www.interchangefinancial.com/ics-service/' \
          -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' \
          -H 'X-Requested-With: XMLHttpRequest' \
          -H 'Origin: https://www.interchangefinancial.com' \
          -H 'DNT: 1' \
          -H 'Connection: keep-alive' \
          --data-raw 'action=non_cash_rate_booking&booking_type=buy&selected_currency_id=16&i_want_amount=666.50&to_amount=5%2C000&change=bct_to_inputfield' | jq '.price')

          echo $RESULT

          if (( $(echo "$RESULT < 1.325" |bc -l) )); then
            echo "whooray"
          fi
          
          curl -X POST --data-urlencode "payload={\"channel\": \"#fx\", \"username\": \"fxbot\", \"text\": \"the USD/CAD price is: ${RESULT}\", \"icon_emoji\": \":ghost:\"}" $CHANNEL_URL  


          
